INSERT INTO `lesson7db`.`user` (`id`,`firstName`,`secondName`,`password`) VALUES (1,'Ivan','Ivanovich','1');
INSERT INTO `lesson7db`.`user` (`id`,`firstName`,`secondName`,`password`) VALUES (2,'Petr','Petrovich','2');
INSERT INTO `lesson7db`.`user` (`id`,`firstName`,`secondName`,`password`) VALUES (3,'Dmitry','Dmitrievich','3');
INSERT INTO `lesson7db`.`user_favouritedishes` (`User_id`,`favouriteDishes`) VALUES (1,'a');
INSERT INTO `lesson7db`.`user_favouritedishes` (`User_id`,`favouriteDishes`) VALUES (1,'b');
INSERT INTO `lesson7db`.`user_favouritedishes` (`User_id`,`favouriteDishes`) VALUES (2,'c');
INSERT INTO `lesson7db`.`user_favouritedishes` (`User_id`,`favouriteDishes`) VALUES (2,'d');
INSERT INTO `lesson7db`.`user_user` (`User_id`, `friends_id`) VALUES (1, 2);
INSERT INTO `lesson7db`.`user_user` (`User_id`, `friends_id`) VALUES (1, 3);
INSERT INTO `lesson7db`.`user_user` (`User_id`, `friends_id`) VALUES (2, 1);
INSERT INTO `lesson7db`.`user_user` (`User_id`, `friends_id`) VALUES (2, 3);