
package com.seprokof.user.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Mon Oct 31 16:35:25 MSK 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "deleteUserResponse", namespace = "http://ws.user.seprokof.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deleteUserResponse", namespace = "http://ws.user.seprokof.com/")

public class DeleteUserResponse {


}

