
package com.seprokof.user.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Mon Oct 31 16:35:25 MSK 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "getAllUsersResponse", namespace = "http://ws.user.seprokof.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllUsersResponse", namespace = "http://ws.user.seprokof.com/")

public class GetAllUsersResponse {

    @XmlElement(name = "return")
    private java.util.List<com.seprokof.user.dao.User> _return;

    public java.util.List<com.seprokof.user.dao.User> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.seprokof.user.dao.User> new_return)  {
        this._return = new_return;
    }

}

