
package com.seprokof.user.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Mon Oct 31 16:35:25 MSK 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "getUserByIdResponse", namespace = "http://ws.user.seprokof.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getUserByIdResponse", namespace = "http://ws.user.seprokof.com/")

public class GetUserByIdResponse {

    @XmlElement(name = "return")
    private com.seprokof.user.dao.User _return;

    public com.seprokof.user.dao.User getReturn() {
        return this._return;
    }

    public void setReturn(com.seprokof.user.dao.User new_return)  {
        this._return = new_return;
    }

}

