
package com.seprokof.user.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Mon Oct 31 16:35:25 MSK 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "getUserById", namespace = "http://ws.user.seprokof.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getUserById", namespace = "http://ws.user.seprokof.com/")

public class GetUserById {

    @XmlElement(name = "arg0")
    private java.lang.Long arg0;

    public java.lang.Long getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.Long newArg0)  {
        this.arg0 = newArg0;
    }

}

