INSERT INTO meraee.user VALUES (1,'Andrey', '', 'Tarasov', '123', '123');
INSERT INTO meraee.user VALUES (2,'Vasya', '', 'Pupkin', '123', '123');
INSERT INTO meraee.usersettings VALUES (1,'Vasya setting', 1 );
INSERT INTO meraee.usersettings VALUES (2,'Andrey setting', 2 );

INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
INSERT INTO meraee.myorder(myTitle,user_id) VALUES ('some order', 1);
